//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0004
    {
        public string A0004_ID { get; set; }
        public string maPhongBan { get; set; }
        public string IDCha { get; set; }
        public string tenPhongBan { get; set; }
        public string diaChi { get; set; }
        public string dienThoai { get; set; }
        public string Email { get; set; }
        public string logo { get; set; }
        public int thuTu { get; set; }
        public bool tinhTrang { get; set; }
        public string CongTyID { get; set; }
    }
}
