//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0003
    {
        public string A0003_ID { get; set; }
        public string A0001_ID { get; set; }
        public string A0002_ID { get; set; }
    
        public virtual A0001 A0001 { get; set; }
        public virtual A0002 A0002 { get; set; }
    }
}
