//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0014
    {
        public string A0014_ID { get; set; }
        public string A0002_ID { get; set; }
        public System.DateTime ngayGui { get; set; }
        public bool tinhTrang { get; set; }
        public Nullable<System.DateTime> ngayResetMatKhau { get; set; }
    
        public virtual A0002 A0002 { get; set; }
    }
}
