//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0016
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A0016()
        {
            this.A0022 = new HashSet<A0022>();
            this.A0028 = new HashSet<A0028>();
            this.A0033 = new HashSet<A0033>();
        }
    
        public string A0016_ID { get; set; }
        public string A0015_ID { get; set; }
        public string A0032_ID { get; set; }
        public string maCongViec { get; set; }
        public string tenCongViec { get; set; }
        public string A0004_ID { get; set; }
        public int STT { get; set; }
        public int loaiCongViec { get; set; }
        public bool trangThai { get; set; }
    
        public virtual A0015 A0015 { get; set; }
        public virtual A0032 A0032 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A0022> A0022 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A0028> A0028 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A0033> A0033 { get; set; }
    }
}
