//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0019
    {
        public string A0019_ID { get; set; }
        public string A0017_ID { get; set; }
        public string A0002_ID { get; set; }
        public string A0004_ID { get; set; }
        public int STT { get; set; }
    
        public virtual A0002 A0002 { get; set; }
        public virtual A0017 A0017 { get; set; }
    }
}
