//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0011
    {
        public string A0011_ID { get; set; }
        public string A0002_ID { get; set; }
        public string hoVaTen { get; set; }
        public System.DateTime IsTime { get; set; }
        public string IPTruyCap { get; set; }
        public string thietBiTruyCap { get; set; }
        public string IPMac { get; set; }
    }
}
