//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0012
    {
        public string A0012_ID { get; set; }
        public string A0002_ID { get; set; }
        public string tieuDe { get; set; }
        public string controller { get; set; }
        public Nullable<System.DateTime> logDate { get; set; }
        public string logContent { get; set; }
        public string hoVaTen { get; set; }
        public Nullable<int> kieuDuLieu { get; set; }
        public string IPTruyCap { get; set; }
        public string thietBiTruyCap { get; set; }
    }
}
