//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0018
    {
        public string A0018_ID { get; set; }
        public string A0015_ID { get; set; }
        public string A0004_ID { get; set; }
        public string tenQuyTrinh { get; set; }
        public int kieuQuyTrinh { get; set; }
        public int STT { get; set; }
        public bool trangThai { get; set; }
    
        public virtual A0015 A0015 { get; set; }
    }
}
