//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0010
    {
        public string A0010_ID { get; set; }
        public string A0001_ID { get; set; }
        public string A0002_ID { get; set; }
        public string A0004_ID { get; set; }
        public string BuaAnID { get; set; }
        public System.DateTime thoiGianGioiHan { get; set; }
        public bool quyenThem { get; set; }
        public bool quyenCapNhap { get; set; }
        public bool quyenXoa { get; set; }
    
        public virtual A0002 A0002 { get; set; }
    }
}
