//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0029
    {
        public string A0029_ID { get; set; }
        public string A0028_ID { get; set; }
        public string A0002_ID { get; set; }
        public string A0017_ID { get; set; }
        public string A0020_ID { get; set; }
        public string tenNhomKy { get; set; }
        public string tenViTri { get; set; }
        public bool daKy { get; set; }
        public int thuThu { get; set; }
        public Nullable<System.DateTime> thoiGianGui { get; set; }
        public bool viTriHienTai { get; set; }
        public bool daXem { get; set; }
    
        public virtual A0002 A0002 { get; set; }
        public virtual A0028 A0028 { get; set; }
    }
}
