//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0023
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A0023()
        {
            this.A0024 = new HashSet<A0024>();
            this.A0026 = new HashSet<A0026>();
        }
    
        public string A0023_ID { get; set; }
        public string A0022_ID { get; set; }
        public string tenHangMuc { get; set; }
        public string tenHangMucKhongDau { get; set; }
        public string nguoiTao { get; set; }
        public System.DateTime ngayTao { get; set; }
        public Nullable<System.DateTime> ngayDuKienHoanThanh { get; set; }
        public string nguoiHoanThanh { get; set; }
        public Nullable<System.DateTime> ngayHoanThanh { get; set; }
        public double phanTramHoanThanh { get; set; }
        public int trangThai { get; set; }
    
        public virtual A0022 A0022 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A0024> A0024 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A0026> A0026 { get; set; }
    }
}
