//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0021
    {
        public string A0021_ID { get; set; }
        public string A0004_ID { get; set; }
        public string A0015_ID { get; set; }
        public string A0017_ID { get; set; }
        public string A0018_ID { get; set; }
        public string A0020_ID { get; set; }
    
        public virtual A0015 A0015 { get; set; }
        public virtual A0017 A0017 { get; set; }
        public virtual A0020 A0020 { get; set; }
    }
}
