//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0024
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A0024()
        {
            this.A0027 = new HashSet<A0027>();
        }
    
        public string A0024_ID { get; set; }
        public string A0023_ID { get; set; }
        public string tenTieuMucHoSo { get; set; }
        public string tenTieuMucHoSoKhongDau { get; set; }
        public string nguoiTao { get; set; }
        public System.DateTime ngayTao { get; set; }
        public Nullable<System.DateTime> ngayDuKienHoanThanh { get; set; }
        public string nguoiHoanThanh { get; set; }
        public Nullable<System.DateTime> ngayHoanThanh { get; set; }
        public double phanTramHoanThanh { get; set; }
        public int trangThai { get; set; }
    
        public virtual A0023 A0023 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A0027> A0027 { get; set; }
    }
}
