//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0028D
    {
        public string A0028D_ID { get; set; }
        public string A0028_ID { get; set; }
        public int IsPostion { get; set; }
        public string C001C { get; set; }
        public string C002C { get; set; }
        public string C003C { get; set; }
        public string C004C { get; set; }
        public string C005C { get; set; }
        public string C006C { get; set; }
        public string C007C { get; set; }
        public string C008C { get; set; }
        public string C009C { get; set; }
        public string C010C { get; set; }
        public string C011C { get; set; }
        public string C012C { get; set; }
        public string C013C { get; set; }
        public string C014C { get; set; }
        public string C015C { get; set; }
        public string C016C { get; set; }
        public string C017C { get; set; }
        public string C018C { get; set; }
        public string C019C { get; set; }
        public string C020C { get; set; }
        public string C021C { get; set; }
        public string C022C { get; set; }
        public string C023C { get; set; }
        public string C024C { get; set; }
        public string C025C { get; set; }
        public string C026C { get; set; }
        public string C027C { get; set; }
        public string C028C { get; set; }
        public string C029C { get; set; }
        public string C030C { get; set; }
        public string C031C { get; set; }
        public string C032C { get; set; }
        public string C033C { get; set; }
        public string C034C { get; set; }
        public string C035C { get; set; }
        public string C036C { get; set; }
        public string C037C { get; set; }
        public string C038C { get; set; }
        public string C039C { get; set; }
        public string C040C { get; set; }
    
        public virtual A0028 A0028 { get; set; }
    }
}
