//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0028
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A0028()
        {
            this.A0029 = new HashSet<A0029>();
            this.A0030 = new HashSet<A0030>();
            this.A0031 = new HashSet<A0031>();
            this.A0028D = new HashSet<A0028D>();
            this.A0037 = new HashSet<A0037>();
        }
    
        public string A0028_ID { get; set; }
        public string A0002_ID { get; set; }
        public string A0016_ID { get; set; }
        public string A0032_ID { get; set; }
        public string T001C { get; set; }
        public string T002C { get; set; }
        public string T003C { get; set; }
        public string T004C { get; set; }
        public string T005C { get; set; }
        public string T006C { get; set; }
        public string T007C { get; set; }
        public string T008C { get; set; }
        public string T009C { get; set; }
        public string T010C { get; set; }
        public string T011C { get; set; }
        public string T012C { get; set; }
        public string T013C { get; set; }
        public string T014C { get; set; }
        public string T015C { get; set; }
        public string T016C { get; set; }
        public string T017C { get; set; }
        public string T018C { get; set; }
        public string T019C { get; set; }
        public string T020C { get; set; }
        public string T021C { get; set; }
        public string T022C { get; set; }
        public string T023C { get; set; }
        public string T024C { get; set; }
        public string T025C { get; set; }
        public string T026C { get; set; }
        public string T027C { get; set; }
        public string T028C { get; set; }
        public string T029C { get; set; }
        public string T030C { get; set; }
        public string T031C { get; set; }
        public string T032C { get; set; }
        public string T033C { get; set; }
        public string T034C { get; set; }
        public string T035C { get; set; }
        public string T036C { get; set; }
        public string T037C { get; set; }
        public string T038C { get; set; }
        public string T039C { get; set; }
        public string T040C { get; set; }
        public string T041C { get; set; }
        public string T042C { get; set; }
        public string T043C { get; set; }
        public string T044C { get; set; }
        public string T045C { get; set; }
        public string T046C { get; set; }
        public string T047C { get; set; }
        public string T048C { get; set; }
        public string T049C { get; set; }
        public string T050C { get; set; }
        public string T051C { get; set; }
        public string T052C { get; set; }
        public string T053C { get; set; }
        public string T054C { get; set; }
        public string T055C { get; set; }
        public string T056C { get; set; }
        public string T057C { get; set; }
        public string T058C { get; set; }
        public string T059C { get; set; }
        public string T060C { get; set; }
        public string T061C { get; set; }
        public string T062C { get; set; }
        public string T063C { get; set; }
        public string T064C { get; set; }
        public string T065C { get; set; }
        public string T066C { get; set; }
        public string T067C { get; set; }
        public string T068C { get; set; }
        public string T069C { get; set; }
        public string T070C { get; set; }
        public string T071C { get; set; }
        public string T072C { get; set; }
        public string T073C { get; set; }
        public string T074C { get; set; }
        public string T075C { get; set; }
        public string T076C { get; set; }
        public string T077C { get; set; }
        public string T078C { get; set; }
        public string T079C { get; set; }
        public string T080C { get; set; }
        public string T081C { get; set; }
        public string T082C { get; set; }
        public string T083C { get; set; }
        public string T084C { get; set; }
        public string T085C { get; set; }
        public string T086C { get; set; }
        public string T087C { get; set; }
        public string T088C { get; set; }
        public string T089C { get; set; }
        public string T090C { get; set; }
        public string T091C { get; set; }
        public string T092C { get; set; }
        public string T093C { get; set; }
        public string T094C { get; set; }
        public string T095C { get; set; }
        public string T096C { get; set; }
        public string T097C { get; set; }
        public string T098C { get; set; }
        public string T099C { get; set; }
        public string T100C { get; set; }
        public string maForm { get; set; }
        public Nullable<int> trangThaiNguoiTao { get; set; }
        public int trangThai { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<System.DateTime> ngayXuLyMongMuon { get; set; }
        public string viTriHienTaiMenuID { get; set; }
        public string viTriHienTaiNhomKyID { get; set; }
        public string viTriHienTaiUserID { get; set; }
        public Nullable<bool> daXoa { get; set; }
    
        public virtual A0002 A0002 { get; set; }
        public virtual A0016 A0016 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A0029> A0029 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A0030> A0030 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A0031> A0031 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A0028D> A0028D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A0037> A0037 { get; set; }
    }
}
