//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0022
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A0022()
        {
            this.A0023 = new HashSet<A0023>();
            this.A0025 = new HashSet<A0025>();
        }
    
        public string A0022_ID { get; set; }
        public string A0016_ID { get; set; }
        public string A0028_ID { get; set; }
        public string soHoSo { get; set; }
        public string tenHoSoKhongDau { get; set; }
        public string tenHoSo { get; set; }
        public string noiDungHoSo { get; set; }
        public string noiDungHoSoKhongDau { get; set; }
        public string nguoiTao { get; set; }
        public string nguoiDong { get; set; }
        public System.DateTime ngayMo { get; set; }
        public Nullable<System.DateTime> ngayDuKienHoanThanh { get; set; }
        public Nullable<System.DateTime> ngayHoanThanh { get; set; }
        public int trangThai { get; set; }
    
        public virtual A0016 A0016 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A0023> A0023 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A0025> A0025 { get; set; }
    }
}
