//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0027
    {
        public string A0027_ID { get; set; }
        public string A0024_ID { get; set; }
        public string A0002_ID { get; set; }
        public int kieuNguoiXuLy { get; set; }
        public System.DateTime ngayThem { get; set; }
        public Nullable<int> thuTu { get; set; }
    
        public virtual A0024 A0024 { get; set; }
    }
}
