//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0038
    {
        public string A0038_ID { get; set; }
        public string A0028D_ID { get; set; }
        public string A0037_ID { get; set; }
        public string A0002_ID { get; set; }
        public string mailNguoiKy { get; set; }
        public Nullable<int> viTri { get; set; }
        public bool viTriHienTai { get; set; }
        public bool daKy { get; set; }
        public Nullable<System.DateTime> thoiGianKy { get; set; }
        public int thuTu { get; set; }
    
        public virtual A0037 A0037 { get; set; }
    }
}
