//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0030
    {
        public string A0030_ID { get; set; }
        public string A0028_ID { get; set; }
        public string A0002_ID { get; set; }
        public string tieuDe { get; set; }
        public string noiDung { get; set; }
        public int thuThu { get; set; }
        public int trangThai { get; set; }
        public System.DateTime thoiGianGui { get; set; }
    
        public virtual A0002 A0002 { get; set; }
        public virtual A0028 A0028 { get; set; }
    }
}
