//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0032
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A0032()
        {
            this.A0016 = new HashSet<A0016>();
        }
    
        public string A0032_ID { get; set; }
        public string maForm { get; set; }
        public string tenForm { get; set; }
        public string tenTiengNhat { get; set; }
        public string formPhongBan { get; set; }
        public Nullable<int> kieuForm { get; set; }
        public string images { get; set; }
        public Nullable<System.DateTime> ngayPhatHanh { get; set; }
        public string nguoiTao { get; set; }
        public Nullable<int> thuTu { get; set; }
        public Nullable<bool> trangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A0016> A0016 { get; set; }
    }
}
