//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0039
    {
        public string A0039_ID { get; set; }
        public string A0028_ID { get; set; }
        public string A0028D_ID { get; set; }
        public string A0037_ID { get; set; }
        public Nullable<System.DateTime> ngayXuLy { get; set; }
        public string nguoiXuLy { get; set; }
        public string noiDungXuLy { get; set; }
        public int trangThai { get; set; }
    
        public virtual A0037 A0037 { get; set; }
    }
}
