//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0037
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A0037()
        {
            this.A0038 = new HashSet<A0038>();
            this.A0039 = new HashSet<A0039>();
        }
    
        public string A0037_ID { get; set; }
        public string A0002_ID { get; set; }
        public string A0028_ID { get; set; }
        public string A0034_ID { get; set; }
        public string tenBoPhan { get; set; }
        public int trangThai { get; set; }
        public bool IsEdit { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<System.DateTime> ngayXuLyMongMuon { get; set; }
        public string viTriHienTaiMenuID { get; set; }
        public string viTriHienTaiUserID { get; set; }
        public Nullable<System.DateTime> ngayHoanThanh { get; set; }
    
        public virtual A0002 A0002 { get; set; }
        public virtual A0028 A0028 { get; set; }
        public virtual A0034 A0034 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A0038> A0038 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A0039> A0039 { get; set; }
    }
}
