//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0036
    {
        public string A0036_ID { get; set; }
        public string A0035_ID { get; set; }
        public string A0034_ID { get; set; }
        public int IsType { get; set; }
    
        public virtual A0034 A0034 { get; set; }
        public virtual A0035 A0035 { get; set; }
    }
}
