//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0031
    {
        public string A0031_ID { get; set; }
        public string A0028_ID { get; set; }
        public string tenFile { get; set; }
        public string dungLuong { get; set; }
        public string duongDan { get; set; }
        public System.DateTime ngayTao { get; set; }
        public string loaiFile { get; set; }
        public int kieuFile { get; set; }
        public int thuTu { get; set; }
    
        public virtual A0028 A0028 { get; set; }
    }
}
