//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0040
    {
        public string A0040_ID { get; set; }
        public string A0034_ID { get; set; }
        public string nguoiKy1 { get; set; }
        public string nguoiKy2 { get; set; }
        public string nguoiKy3 { get; set; }
        public string nguoiKy4 { get; set; }
        public string nguoiKy5 { get; set; }
        public string nguoiKy6 { get; set; }
        public string nguoiKy7 { get; set; }
        public string MailNguoiKy1 { get; set; }
        public string MailNguoiKy2 { get; set; }
        public string MailNguoiKy3 { get; set; }
        public string MailNguoiKy4 { get; set; }
        public string MailNguoiKy5 { get; set; }
        public string MailNguoiKy6 { get; set; }
        public string MailNguoiKy7 { get; set; }
    }
}
