//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0044
    {
        public string A0044_ID { get; set; }
        public string Parent_ID { get; set; }
        public string boPhan_ID { get; set; }
        public string tenBoPhan { get; set; }
        public int thang { get; set; }
        public int nam { get; set; }
        public int chiTieuBai { get; set; }
    }
}
