//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0041
    {
        public string A0041_ID { get; set; }
        public string tenEmail { get; set; }
        public string Email { get; set; }
        public string PassWord { get; set; }
        public int Port { get; set; }
        public string SMTPIn { get; set; }
        public string SMTPOut { get; set; }
    }
}
