//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A0043
    {
        public string A0043_ID { get; set; }
        public string tenKieuBaiViet { get; set; }
        public int kieuBaiViet { get; set; }
        public double giaTri { get; set; }
        public int STT { get; set; }
    }
}
