//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    
    public partial class List_ThamSoDungChung_Result1
    {
        public string ghiChu { get; set; }
        public string maCode { get; set; }
        public string Module { get; set; }
    }
}
