//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MeikoEntities : DbContext
    {
        public MeikoEntities()
            : base("name=MeikoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A0001> A0001 { get; set; }
        public virtual DbSet<A0002> A0002 { get; set; }
        public virtual DbSet<A0003> A0003 { get; set; }
        public virtual DbSet<A0004> A0004 { get; set; }
        public virtual DbSet<A0005> A0005 { get; set; }
        public virtual DbSet<A0006> A0006 { get; set; }
        public virtual DbSet<A0007> A0007 { get; set; }
        public virtual DbSet<A0008> A0008 { get; set; }
        public virtual DbSet<A0009> A0009 { get; set; }
        public virtual DbSet<A0010> A0010 { get; set; }
        public virtual DbSet<A0011> A0011 { get; set; }
        public virtual DbSet<A0012> A0012 { get; set; }
        public virtual DbSet<A0013> A0013 { get; set; }
        public virtual DbSet<A0014> A0014 { get; set; }
        public virtual DbSet<A0015> A0015 { get; set; }
        public virtual DbSet<A0016> A0016 { get; set; }
        public virtual DbSet<A0017> A0017 { get; set; }
        public virtual DbSet<A0018> A0018 { get; set; }
        public virtual DbSet<A0019> A0019 { get; set; }
        public virtual DbSet<A0020> A0020 { get; set; }
        public virtual DbSet<A0021> A0021 { get; set; }
        public virtual DbSet<A0022> A0022 { get; set; }
        public virtual DbSet<A0023> A0023 { get; set; }
        public virtual DbSet<A0024> A0024 { get; set; }
        public virtual DbSet<A0025> A0025 { get; set; }
        public virtual DbSet<A0026> A0026 { get; set; }
        public virtual DbSet<A0027> A0027 { get; set; }
        public virtual DbSet<A0028> A0028 { get; set; }
        public virtual DbSet<A0028D> A0028D { get; set; }
        public virtual DbSet<A0029> A0029 { get; set; }
        public virtual DbSet<A0030> A0030 { get; set; }
        public virtual DbSet<A0031> A0031 { get; set; }
        public virtual DbSet<A0032> A0032 { get; set; }
        public virtual DbSet<A0033> A0033 { get; set; }
        public virtual DbSet<A0034> A0034 { get; set; }
        public virtual DbSet<A0035> A0035 { get; set; }
        public virtual DbSet<A0036> A0036 { get; set; }
        public virtual DbSet<A0037> A0037 { get; set; }
        public virtual DbSet<A0038> A0038 { get; set; }
        public virtual DbSet<A0039> A0039 { get; set; }
        public virtual DbSet<A0040> A0040 { get; set; }
        public virtual DbSet<A0041> A0041 { get; set; }
        public virtual DbSet<A0042> A0042 { get; set; }
        public virtual DbSet<A0043> A0043 { get; set; }
        public virtual DbSet<A0044> A0044 { get; set; }
    
        public virtual ObjectResult<List_ThamSoDungChung_Result1> List_ThamSoDungChung(string tenTieuDe)
        {
            var tenTieuDeParameter = tenTieuDe != null ?
                new ObjectParameter("tenTieuDe", tenTieuDe) :
                new ObjectParameter("tenTieuDe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<List_ThamSoDungChung_Result1>("List_ThamSoDungChung", tenTieuDeParameter);
        }
    
        public virtual ObjectResult<R1_List_PhanQuyen_Result3> R1_List_PhanQuyen(string a0001_ID, string a0002_ID)
        {
            var a0001_IDParameter = a0001_ID != null ?
                new ObjectParameter("A0001_ID", a0001_ID) :
                new ObjectParameter("A0001_ID", typeof(string));
    
            var a0002_IDParameter = a0002_ID != null ?
                new ObjectParameter("A0002_ID", a0002_ID) :
                new ObjectParameter("A0002_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<R1_List_PhanQuyen_Result3>("R1_List_PhanQuyen", a0001_IDParameter, a0002_IDParameter);
        }
    }
}
