//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    
    public partial class R1_List_PhanQuyen_Result1
    {
        public string MenuID { get; set; }
        public string tenMenu { get; set; }
        public string Icon { get; set; }
        public int thuThu { get; set; }
        public string IDCha { get; set; }
        public string RoleID { get; set; }
        public bool quyenXem { get; set; }
        public bool quyenThem { get; set; }
        public bool quyenCapNhap { get; set; }
        public bool quyenXoa { get; set; }
    }
}
